apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appppsss
  namespace: argocd
spec:
  project: default
  source:
    path: demo
    repoURL: https://github.com/Emc285/argocd-helm-demo.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
        - 'configs/**/values.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: tst