apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tst-apps
  namespace: argocd
spec:
  project: default
  source:
    path: demo
    repoURL: https://github.com/Emc285/argocd-helm-demo.git
    targetRevision: feature
    helm:
      valueFiles:
        - values.yaml
        - configs/tst/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tst
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tst-app-main
  namespace: argocd
spec:
  project: default
  source:
    path: demo
    repoURL: https://github.com/Emc285/argocd-helm-demo.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
        - configs/tst/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tst