apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-app
spec:
  spec:
    project: default
    source:
      path: helm/tst
      repoURL: https://github.com/Emc285/JT-values-argocd.git
      targetRevision: main
    destination:
      server: https://kubernetes.default.svc
      namespace: tst